config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :users, except: [:index]

  # resource :user do
  #   collection do
  #     get :history
  #   end
  # end

  resources :categories
  resource :session, only: [:new, :create, :destroy]

  resources :animals, except: [:destroy] do
    member do
      patch 'adopt'
    end

    collection do
      get 'waiting_for_adoption', :path => 'waiting-for-adoption'
    end
  end

   get '/about' => 'pages#about'
   get '/faq' => 'pages#faq'
   get '/contact' => 'pages#contact'
   get '/pawswalk' => 'pages#pawswalk'
   get '/info' => 'pages#info'
   get '/donate' => 'pages#donate'
end

app/models/animal.rb
# == Schema Information
#
# Table name: animals
#
#  id             :integer          not null, primary key
#  adopter_id     :integer
#  adoptee_id     :integer
#  animal_id      :integer
#  name           :string(255)
#  about_me       :text
#  ideal_home     :string(255)
#  species        :string(255)
#  gender         :string(255)
#  child_friendly :string(255)
#  image          :text
#  created_at     :datetime
#  updated_at     :datetime
#  category_id    :integer
#

class Animal < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :category

  belongs_to :adoptee, class_name: "User" # , primary_key: "adoptee_id"
  belongs_to :adopter, class_name: "User" # , primary_key: "adopter_id"

  SPECIES = [
    OpenStruct.new(value: "Dog", text: "Dog"),
    OpenStruct.new(value: "Cat", text: "Cat")
  ]

  validates :name, presence: true
  validates :about_me, presence: true
  validates :ideal_home, presence: true

  # SPECIES = %w[Dog Cat]
  # validates :species, inclusion: { in: SPECIES }

  GENDER = %w[Male Female]
  validates :gender, inclusion: { in: GENDER }

  CHILD_FRIENDLY = [true, false]
  validates :child_friendly, inclusion: { in: CHILD_FRIENDLY }

  def adopt! adopter
    update adopter_id: adopter.id
  end

  def adopted?
    return !adopter_id.nil?
  end
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Category < ActiveRecord::Base
  has_many :animals
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  firstname       :string(255)
#  lastname        :string(255)
#  email           :string(255)
#  password_digest :text
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base

  has_many :adoptions, class_name: "Animal", :foreign_key => 'adopter_id'
  has_many :surrenders, class_name: "Animal", :foreign_key => 'adoptee_id'

  # validates :email, :uniqueness => true
  validates :email, confirmation: true
  validates :firstname, :lastname, :email, :password, :presence => true
  validates_length_of :password, in: 3..20, on: :create
  has_secure_password
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_filter :authorize, only: [:new, :create, :adopt]

  def new
    @animal = current_user.surrenders.new
  end

  def create
    @animal = current_user.surrenders.new animal_params

    if @animal.save
      redirect_to @animal, notice: 'Animal successfully created and waiting for adoption'
    else
      render :new
    end
  end

  def index
    @animals = if params[:category].present?
      category = Category.where(name: params[:category]).first
      Animal.where category_id: category.id
    else
      Animal.all
    end
  end

  def show
    @animal = Animal.find params[:id]
  end


  def adopt
    @animal = Animal.find params[:id]

    @animal.adopt! current_user

    redirect_to @animal, notice: 'Animal successfully adopted'  
  end

  def waiting_for_adoption
    @animals = Animal.where adopter_id: nil

    render :index
  end

  def edit
  end

  private

  def animal_params
    params.require(:animal).permit(:name, :about_me, :ideal_home, :species, :gender, :child_friendly, :breed, :image, :image_cache, :remote_image_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  before_action :authenticate

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  private

  def authenticate
    session[:user_id] = nil if user_logged_in?
  end

  def check_login
    redirect_to new_user_path if user_logged_in?
  end

  def authorize
    redirect_to new_session_path if user_logged_in?
  end

  def user_logged_in?
    current_user.nil?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category  = Cartegory.find params[:id]
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def adopt
  end

  def pawswalk
  end

  def donate
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.where(:email => params[:session][:email]).first
    if user.present? && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path, :flash => {:notice => "Welcome back, #{ user.firstname }"}
    else
      redirect_to new_session_path, :flash => {:error => 'Incorrect login'}
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, :flash => {:notice => 'You are now signed out'}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, :flash => {:notice => "Welcome to Animal Rescue #{ @user.firstname }"}
    else
      render :new
    end
  end

  def edit
    @user = @current_user
  end

  def update
    user = @current_user
    user.update user_params
    redirect_to user
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
    # binding.pry
  end

  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_form.html.haml
.surrender-animal
  = form_for @animal, :html => {:multipart => true} do |f|
    - if @animal.errors.any?
      %ul
        - @animal.errors.full_messages.each do |msg|
          %li= msg

    %div.form-group
      = f.label :name
      = f.text_field :name, :autofocus => true, :class => 'form-control'

    %div.form-group
      = f.label :about_me
      = f.text_field :about_me, :class => 'form-control'

    %div.form-group
      = f.label :species
      %p
      = f.collection_select(:species, Animal::SPECIES, :value, :text)

    %div.form-group
      = f.label :breed
      = f.text_field :breed, :class => 'form-control'

    %div.form-group
      = f.label :gender
      %p.gender
        = f.label "Male"
        = f.radio_button :gender, "Male", value: 'checked', :class => 'form-control' 

        = f.label "Female"
        = f.radio_button :gender, "Female", :class => 'form-control' 
    %div.form-group
      = f.label :ideal_home
      = f.text_field :ideal_home, :class => 'form-control'

    %div.form-group
      = f.label :child_friendly
      %p.child-friendly
        = f.label "Yes"
        = f.radio_button :child_friendly, "Yes", value: 'true', :class => 'form-control'

        = f.label "No"
        = f.radio_button :child_friendly, "No", value: 'false', :class => 'form-control'

    %div.form-group
      = f.label :image
      %br
      = f.file_field :image
      = f.hidden_field :image_cache
      = f.text_field :remote_image_url, :placeholder => "Image Url"


    %label
    = f.submit

app/views/animals/index.html.haml
/ .grid
/   - @animals.each do |animal|
/     %figure#animals.effect-lily
/       %img{:style => "background-image:url(#{ animal.image }) background-repeat:none"}
/       = image_tag animal.image
/       / %figcaption
/         %h2.animal-name
/           = link_to animal.name, animal_path(animal)
/           %span.animal-name
/         %p 
/           = animal.gender

 



.animals-index-heading
  %h2
    Animals
.animals-index
  %ul.photo-grid
    - @animals.each do |animal|
      / = link_to animal_path(animal)
      %li
        .animal_box
          .animal-image{:style => "background-image:url(#{ animal.image })"}
            /= image_tag animal.image
            %div.info
              %h4.animal-name
                = link_to animal.name, animal_path(animal)
              %p.animal-info
                #{animal.gender}
    .clear

app/views/animals/new.html.haml
%h2 Find a new home for my pet

= render 'form'

app/views/animals/show.html.haml
.show-animal
  %h2.col-md-8 
    =@animal.name 
  / .col-md-7
  /   %h3 Species
  /   =@animal.species
  .col-md-7
    %h3 About Me
    =@animal.about_me
  .col-md-7
    %h3 My Ideal Home
    =@animal.ideal_home
  .col-md-7
    %h3 Gender
    =@animal.gender
  .col-md-7
    %h3 Child Friendly
    = @animal.child_friendly ? "Yes" : "No"

.animal-image
  %img{:src => @animal.image}
  - if @animal.adopted?
    %h4 This animal under the process of being adopted
  - else
    - if current_user 
      = form_for @animal, url: adopt_animal_path(@animal), method: 'patch' do
        = submit_tag 'Adopt me'
    - else
      = link_to "Log in to adopt", new_session_path
.col-md-7
  = link_to "Go Back", animals_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="<%= params[:controller] %>-<%= params[:action] %>">
<head>
  <title>Shelter</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>


<nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Animal Rescue</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
              <ul class="nav navbar-nav">
                <li><%= link_to 'Adopt', waiting_for_adoption_animals_path %></li>
                <li><%= link_to 'FAQ', faq_path %></li><li>
                <!-- <li><%#= link_to 'Contact', contact_path %></li> -->
                <li><%= link_to 'About', about_path %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Search for Species <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Dogs", animals_path(category: "Dogs") %></li>
                    <li><%= link_to "Cats", animals_path(category: "Cats") %></li>
                  </ul>
                </li>
              <% if @current_user.present? %>
                <li class="loggedin"><%= link_to 'Surrender your pet', new_animal_path %></li>
                <li class="loggedin"><%= link_to 'Profile', user_path(@current_user) %></li>
                <li class="loggedin"><%= link_to "Sign out #{@current_user.firstname}", session_path, method: :delete, data: { confirm: 'Are you sure?'} %></li>
              <% else %>
                  <li class="login"><%= link_to 'Sign up', new_user_path %></li>
                  <li class="login"><%= link_to 'Login', new_session_path %></li>
              <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    <div class="container">
      <% {:notice => 'info', :error => 'danger' }.each do |k,v| %>
        <% if flash[k].present? %>
         <div class="alert alert-<%= v %> row" role="alert"><%= flash[k] %></div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/pages/about.html.haml
.carousel-inner{:role => "listbox"}
  .container
    .carousel-caption
      %h1 About Us
      %p
        / %a.btn.btn-lg.btn-default{:href => "/animals", :role => "button"} All our animals


.infoboxes
  %article.span3
    %img{:alt => "", :src => "http://upload.wikimedia.org/wikipedia/commons/0/0a/Paw_(Animal_Rights_symbol).png"}
      %h3
        = link_to "Get Involved", pawswalk_path
      %p Some of the animals entering shelters need a little extra help before they are ready for adoption and their new forever homes. Our foster care program helps these animals recover in a home environment until they’re ready to enter adoption.
  %article.span3
    %img{:alt => "", :src => "http://cdn.flaticon.com/png/256/33715.png"}
      %h3
        %a{:href => "http://upload.wikimedia.org/wikipedia/commons/0/0a/Paw_(Animal_Rights_symbol).png", :title => "Volunteer"} Volunteer
      %p Are you dedicated and willing to make a regular commitment to help animals – animals that have been displaced, abandoned and possibly neglected and abused? If so, you may be just the person we are looking for to become an Animal Rescue Volunteer.
  %article.span3
    %img.donate{:alt => "", :src => "http://dvsiteimages20948.s3.amazonaws.com/wp-content/uploads/2014/09/Giving-Icon.png"}
      %h3
        = link_to "Donate", donate_path
      %p Are you dedicated and willing to make a regular commitment to help animals – animals that have been displaced, abandoned and possibly neglected and abused? If so, you may be just the person we are looking for to become an Animal Rescue Volunteer.

  %article.span3
    %img{:alt => "", :src => "https://cdn3.iconfinder.com/data/icons/wpzoom-developer-icon-set/500/105-128.png"}
      %h3
        = link_to "About Us", info_path
      %p Are you dedicated and willing to make a regular commitment to help animals – animals that have been displaced, abandoned and possibly neglected and abused? If so, you may be just the person we are looking for to become an Animal Rescue Volunteer.

app/views/pages/contact.html.haml
.carousel-inner{:role => "listbox"}
  .container
    .carousel-caption
      %p Animal Rescue is a not for profit, volunteer run, non government organization.
      %p
        %a.btn.btn-lg.btn-default{:href => "/animals", :role => "button"} All our animals
/ /.carousel
/ %section#services
.animation-target

  .infoboxes
    %article.span3
      %img{:alt => "", :src => "http://upload.wikimedia.org/wikipedia/commons/0/0a/Paw_(Animal_Rights_symbol).png"}
        %h3
          = link_to "Get Involved", pawswalk_path
        %p Some of the animals entering shelters need a little extra help before they are ready for adoption and their new forever homes. They may be too young, unwell, recovering from surgery, or may need training to improve their behaviour. Our foster care program helps these animals recover in a home environment until they’re ready to enter adoption.
    %article.span3
      %img{:alt => "", :src => "http://cdn.flaticon.com/png/256/33715.png"}
        %h3
          %a{:href => "http://upload.wikimedia.org/wikipedia/commons/0/0a/Paw_(Animal_Rights_symbol).png", :title => "Volunteer"} Volunteer
        %p Are you dedicated and willing to make a regular commitment to help animals – animals that have been displaced, abandoned and possibly neglected and abused? If so, you may be just the person we are looking for to become an Animal Rescue Volunteer.
    %article.span3
      %img.donate{:alt => "", :src => "http://dvsiteimages20948.s3.amazonaws.com/wp-content/uploads/2014/09/Giving-Icon.png"}
        %h3
          %a{:href => "http://upload.wikimedia.org/wikipedia/commons/0/0a/Paw_(Animal_Rights_symbol).png", :title => "Get Involved"} Donate
        %p Every day, thousands of pets are counting on us to find them a forever home. We know you can't take them all home, but you can help us keep saving lives and stop the killing of healthy and treatable companion animals in Australia’s pounds.

app/views/pages/donate.html.haml
%h2 Donate

.faqdog
  %img{:src => "http://www.beenleighfarmsupplies.com.au/eshop/images/C/dog%202.jpg", :alt => ""}/

%p Every day, thousands of pets are counting on us to find them a forever home. We know you can't take them all home, but you can help us keep saving lives and stop the killing of healthy and treatable companion animals in Australia’s pounds.

%p Our not-for-profit organisation empowers pet-loving Australians to adopt more than 5,000 rescue pets every month, and discover the joy of unconditional love a rescue pet brings. That’s saving 5,000+ orphaned pets that may otherwise go unnoticed or, worse still, be euthanised.

%p It costs just $25 to match one of our rescue pets with their new family. 
%p If you're an animal lover you can save a life.

.donate-page
  = form_for current_user, :html => {:multipart => true} do |f|

    %div.form-group
      = f.label :firstname
      = f.text_field :firstname, :autofocus => true, :class => 'form-control'
    %div.form-group
      = f.label :email
      = f.text_field :email, :class => 'form-control'
    / %div.form-group
    /   = f.label :donate
    /   = f.text_field :donate, :class => 'form-control'
    %label
    = f.submit "Donate"

app/views/pages/faq.html.haml
%h2 Frequently Asked Questions

.faqdog
  %img{:src => "http://www.beenleighfarmsupplies.com.au/eshop/images/C/dog%202.jpg", :alt => ""}/

%h3 What is foster caring?

%p Foster caring is when you take a dog or cat into your home until a forever home can be found. Carers find their role to be very rewarding and love the fact they save the lives of many animals per year.

%h3 If I find a stray animal, will Animal Rescue take it?

%p No, Animal Rescue are not legally permitted to take any stray animals into care.
You need to call your local pound or council, or you can take the animal to a vet to be scanned for a microchip. The vet can contact the owner and advise them where their pet is. If the animal isn’t microchipped, the owners shoul start looking for their lost cat or dog at the pound. If anyone holds onto an animal without letting authorities know, there is no chance it can be reunited with its owner. Animal Rescue urges every animal owner to make sure their pets are wearing collar and identification 24/7

%h3 There is a public listing section on your website, what does that mean?

%p These cats and dogs belong to people who can no longer keep them but don’t want to surrender them to a pound. They are still living with their owners and are being advertised on our site to help promote them. We only allow desexed animals to be advertised. Animal Rescue is not linked to these animals at all and urge the public to ask many questions about behaviours, health, likes, dislikes etc. as we can’t guarantee that what has been written is true and correct. There is a big chance no trial period will be given

%h3 Can Animal Rescue take my pet?

%p Generally, we are not in a position to accept privately surrendered animals as all of our foster carers homes are normally full with priority pound animals. We do have a private surrender page on our website in which we explain the process. We will consider your animal if it has had full vet work and you are prepared to pay the surrender fee BUT this still depends on our foster carer availability.
%p Don’t forget everyone is welcome to list on our public listing page as long as the animal is desexed. This would mean that you would hold onto your pet at home and any enquiries would be directed to you. In return for the free advertisement it is greatly appreciated if a donation can be made to Animal Rescue to help us assist more animals in need.

%h3 Can I foster if I already own pets?

%p Definitely, as long as your pet is vaccinated and desexed.

%h3 Does the foster carer get to pick what animal they foster?

%p Foster carers will be sent a weekly email from our Pound Co-ordinators. It will have the basic details of all available animals plus a photo.
If you would like to foster a particular animal you just reply to the email stating your preference. You will have to be available to pick up the animal from the pound, unless a transport request can be fulfilled.
%p The final decision regarding who adopts your foster animal is always left with you. If you are not happy with, or if you feel uncomfortable with any potential adopting family, the animal will stay with you until the right family comes along.

%h3 Does the foster carer get to pick the new family?

%p Foster carers do decide who gets to meet their foster animals. To make the process easier we have an adoption application form that potential new owners must fill in. This helps you match a suitable new owner to a suitable animal.

%h3 Is it hard when your foster animal goes to its forever home?

%p Although we do miss our foster animals (at times), it’s very satisfying to know that you saved a dog or cat’s life and have now found it an amazing forever home. Don’t forget that there is always another animal at the pound waiting for your help.

%h3 If I have problems, or need help with any foster animals that I am caring for, what can I do?

%p We have a large support system within Animal Rescue. You will have a foster carer co-ordinator which is there to help you! In addition to this person we have an animal committee that are all foster carers themselves with years of experience. We have numerous vets that help Animal Rescue and we encourage our foster carers to work together and stay in touch at regular meetings and events. Also make sure you join our facebook page and chat with other Animal Rescue supporters.

%h3 Who pays for the food and medication?

%p Animal Rescue covers all medical procedures and medications and we regularly have donations for our foster carers which include bedding, food, toys, kennels etc. Carers only need to supply love, shelter and food when donations aren’t available. Contact our donation co-ordinator for list of available items

%h3 Who pays the vet bills for animals in foster care?

%p Animal Rescue pays for all approved vet work; you must have a vet voucher.

%h3 How old must I be if I want to become a foster carer?

%p If you are under 18 year old and are living at home please get your parents permission and ask them to apply.

%h3 How long does a foster carer have an animal for?

%p This depends on the animal. Some animals are receiving enquiries as soon as they go on the website, others are in care for months. It is very important that carers promote their fosters as well as they can. Update photos regularly, spend time getting a good photo and get to know the animal before writing their biography. Make sure you update the bio as you learn more about their behaviours, likes, dislikes. If you have rehoming problems speak to your carer co-ordinator. Feel free to promote your fosters on other websites, make signs, promote on facebook, create a video clip to add to their bio. This really adds personality, we also have pet adopt me shirts for public events.

%h3 Why don’t you give your animals away for free?

%p The adoption fee covers the animal’s full vet work. We also give them worm and flea treatment while in care and treat any medical problem arising while in care.
Animal Rescue also pays for dogs and adult cats lifetime registration with the NSW registry. Please read individual pages for full details.
Some animals require major operations and rehabilitation. These fees are not passed onto the new owners. Animal Rescue covers this by fundraising & donations.
Please note that the adoption fee merely covers the basic vet work done to an animal. Animal Rescue does not make much (if any) profits from the adoption fee.

%h3 If I already have another pet, is it possible to bring it along to meet  an animal that I would like to foster?

%p Yes, there is no problem with this. You will need to mention this to the pound co-ordinator or your foster carer co-ordinator. Keep in mind some animals can take a few days to warm up to each other

%h3 Does Animal Rescue accept animals back? (previous Animal Rescue animal)

%p Always call Animal Rescue first if you can’t keep the animal you adopted from us, no matter how long ago it was.
%p This animal will come back into care as a priority but this will depend on carer availability. Please keep in mind we are all volunteers and most of us work full time in our “real jobs”. Please give us as much notice as possible.
Please don’t contact us and say “We are moving away tomorrow, come pick up the dog or it is going to the pound”. We will unfortunately not be able to help.
Also every new owner has a 2 week trial. If it doesn’t work out they can arrange a time to drop the animal back to its carer and a refund cheque will be posted to them.

%h3 I don’t live in NSW, is it still possible to adopt one of your animals?

%p Animal Rescue doesn’t favor interstate adoption, it will need to have committee approval. We also prefer the owner to meet the animal before it is transported. Pet transport can be very expensive and will be the responsibility of the new owner to cover the costs and pay for the animal to be returned if the trial is unsuccessful. Please keep in mind most areas have an animal rescue or pound so try locally first.

%h3 Do you do yard inspections?

%p Yes. If you are out of our area we will try and find someone else to do the inspection for us (another rescue group). At a minimum we will request digital photos of your property.
We must ensure all our animals are safe and can’t get under or over fences and have basic shelter provided (shade etc).

%h3 Will the animal be healthy?

%p We make sure all possible vet work is completed before going to a new home. Any vet problems that occur during the trial period will be covered by Animal Rescue but must be approved and conducted at certain vet practices. If we are aware of any problems with an animal, there is always full disclosure on the website of the animal’s condition.

%h3 Do you have a shelter?

%p No, all our animals are cared for in our foster carer’s own homes. If you are interested in an animal, you will need to contact the foster carer directly (there will always be a phone number or an email on the biography) to organise a visit/play date and to get more information and ask any questions you may have.

app/views/pages/home.html.haml
.site-wrapper
  .site-wrapper-inner
    .cover-container
      .masthead.clearfix
        .inner
      .inner.cover
        %h1.cover-heading Animal Rescue
        %p.lead
          Animal Rescue is a not for profit, volunteer run, non government organization.
        %p.lead
          %a.btn.btn-lg.btn-default{:href => "/animals", :role => "button"} All our animals
      .mastfoot
        .inner
          %p
            © 2014 Angela ~

app/views/pages/info.html.haml
%h2 What we Do

.faqdog
  %img{:src => "http://www.beenleighfarmsupplies.com.au/eshop/images/C/dog%202.jpg", :alt => ""}/

%p.about Animal Rescue is an Australia-wide not-for-profit organisation inspiring a whole nation to discover the joy and unconditional love a rescue pet brings.

%p.about With the awesome support of our growing community of pet lovers, PetRescue has become Australia’s most visited charity website. Every day we bring pet seekers face-to-furry-face with thousands of adorable rescue pets from shelters and rescue groups nationwide, empowering Australians to save over 6,000 lives every month. Find out more about us here.

%p.about Dogs rescued from the pound are microchipped, heartworm tested and vaccinated by a veterinarian, who also gives them a basic health check and provides us with an estimate of their age. The dogs are desexed (if required) and given any additional veterinary treatment to return them to good health.

%p.about All of the rescued dogs are then cared for, awaiting adoption into a permanent loving home. Once the dogs have completed 8-10 days quarantine (so we can observe them for any illnesses they may have picked up) they stay at our shelter, Doggiewood at Ingleside in the northern beaches of Sydney or can be placed into a foster home.

%p.about We have over 200 dogs up for adoption. They are all featured on this site. Over a year we save about 500 dogs.

%p.about We ask re-imbursement for the basic desexing, vaccination, microchipping and heartworm testing only - generally between $350 and $500.

app/views/pages/pawswalk.html.haml
.pawswalkbanner
  %img{:src => "http://www.millionpawswalk.com.au/Assets/RSPCA+Digital+Assets/NSW/2014/Slideshow/5.+Thank+You.png", :alt => ""}/
  .col-md-5
    %p Million Paws Walk has come to an end for 2014 and we have yet again had a very successful event! Thank you to everyone who participated on the da8 and we appreciate all the amazing support.

    %p Fundraising for Million Paws Walk is still open until June 29. To find all the information about the fundraising competitions, please click here.

    %p The photos from Million Paws Walk 2014 have been uploaded! Click here to view the photo album. Please also see at the bottom of this page the video from the Sydney event.

    %p Missed out on receiving a Participation Certificate on the day? No need to worry! You can download and print a Participation Certificate here. Write your name on it and show it off to your friends and family.

    %p If you want to personally thank your friends and family for their kind donations on your fundraising page, you can download a Certificate of Appreciation. Print it out, write their name and surprise them with an official Million Paws Walk Certificate

  .col-md-7
    %div{:style => "text-align: left; margin: auto"}
      %object{:data => "http://www.youtube.com/v/zeP182srBOY?color2=FBE9EC&hd=1&version=3", :style => "width:640px; height:363px;", :type => "application/x-shockwave-flash"}
        %param{:name => "movie", :value => "http://www.youtube.com/v/zeP182srBOY?color2=FBE9EC&hd=1&version=3"}/
        %param{:name => "allowFullScreen", :value => "true"}/
        %param{:name => "allowscriptaccess", :value => "always"}/
      %div{:style => "font-size: 0.8em"}
      

app/views/users/edit.html.haml
/ .form
/   %h3 Edit User Profile
/ = render :partial => 'form'

%h2
  Edit User Profile
  = @user.firstname

= form_for @user do |f|
  %div
    = f.label :email
    = f.email_field :email

  %div
    = f.label :password
    = f.password_field :password

  %div
    = f.label :password_confirmation
    = f.password_field :password_confirmation

  = f.submit

app/views/users/new.html.haml
.form
  %h3.newuser New User
= render :partial => 'form'

app/views/users/show.html.haml
/ =@user.firstname
.show-animal-profile
  - if @user.present? && @user.adoptions.any?

    - @user.adoptions.each do |animal|
      %h2= link_to animal.name, animal
      %p= animal.about_me
  - else
    %p There are no animals to display.

=link_to 'Edit Profile', edit_user_path(@user)
/ =link_to 'Edit surrendered animal information', edit_animal_path(@animal)